Traceback (most recent call last):
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pyvis.network import Network

# Create a pyvis Network object
net = Network(height = "700px", width = "700px", notebook = True, cdn_resources='remote')

node_sizes = [2 * G.degree(n) for n in G.nodes()]
            
# Set node sizes and colors
for i, name in enumerate(G.nodes):
    G.nodes[name]['size'] = node_sizes[i]
    G.nodes[name]['color'] = "lightblue" if name == 0 or name == 33 else "crimson"

# Set edge color
for i in G.edges:
    G.edges[i]['color'] = "grey"

net.from_nx(G)
net.show('out1.html')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyvis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnetwork[39;00m [38;5;28;01mimport[39;00m Network
[1;32m      3[0m [38;5;66;03m# Create a pyvis Network object[39;00m
[1;32m      4[0m net [38;5;241m=[39m Network(height [38;5;241m=[39m [38;5;124m"[39m[38;5;124m700px[39m[38;5;124m"[39m, width [38;5;241m=[39m [38;5;124m"[39m[38;5;124m700px[39m[38;5;124m"[39m, notebook [38;5;241m=[39m [38;5;28;01mTrue[39;00m, cdn_resources[38;5;241m=[39m[38;5;124m'[39m[38;5;124mremote[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'pyvis'

